### PR TITLE
fix: BREAKING CHANGE Changed params and paths for calibration

### LINKED ISSUE #118: [Calibration] update the paths to their new format
blocked by

- [x] https://github.com/ospin-web-dev/hambda/issues/1789

POST/DELETE /devices/deviceId/configuration/fctGraphId/calibrations

should be a breaking change

### PR DESCRIPTION
**Pull request by FelixMZ2018**
[BREAKING CHANGE](fix: BREAKING CHANGE Changed params and paths for calibration)

### CODE REVIEW

File: src/device/functionality/calibration/remove.js [hunk 1]
```diff
@@ -10,12 +10,17 @@ const { DEFAULT_REQ_OPTS } = require('../../../utils/defaultReqOpts')
...
+ * @param {string} params.fctGraphId
  * @param {string} params.fctId
  * @param {string} params.slotName
  * @returns {Promise<ApiResponse>}
  */
 
 module.exports = serializeAxiosResponse(
-  ({ deviceId, fctId, slotName }) => API
-    .patch('device', `${deviceId}/functionalities/${fctId}/calibrations`, { body: { slotName }, ...DEFAULT_REQ_OPTS }),
+  ({ deviceId, fctGraphId, fctId, slotName }) => API
```
Comment (FelixMZ2018) [inline src/device/functionality/calibration/remove.js]: if we want to be consistent this should probably be (deviceId,fctGraphId,fctId, body

Comment (vdiezel) [reply src/device/functionality/calibration/remove.js]: Then go for it :P

**Review by vdiezel — DISMISSED** [review]

File: src/device/functionality/calibration/update.js [hunk 2]
```diff
@@ -8,27 +8,16 @@ const { DEFAULT_REQ_OPTS } = require('../../../utils/defaultReqOpts')
...
- * @param {Object} params.params.offset
- * @param {Object} params.params.slope
- * @param {number} params.params.offset.value
- * @param {boolean} params.params.offset.locked
- * @param {number} params.params.slope.value
- * @param {boolean} params.params.slope.locked
+ * @param {string} deviceId
+ * @param {string} fctGraphId
+ * @param {string} fctId
+ * @param {string} slotName
```
Comment (vdiezel) [inline src/device/functionality/calibration/update.js]: slotName is not passed anymore here

File: src/device/functionality/calibration/update.js [hunk 3]
```diff
@@ -8,27 +8,16 @@ const { DEFAULT_REQ_OPTS } = require('../../../utils/defaultReqOpts')
...
+ * @param {Object} payload
```
Comment (vdiezel) [inline src/device/functionality/calibration/update.js]: are we calling this `payload` or `body` in the docs? Just want to make sure it is consistent

Comment (vdiezel) [reply src/device/functionality/calibration/update.js:15]: I like the approach of using the full body as the parameter instead of building it from the single props. 
But I think we still should keep the docks for expected properties. How would you know otherwise what the expected properties are?

Comment (vdiezel) [reply src/device/functionality/calibration/update.js:15]: I know that is is somewhat inconsistent, as when something changes, you would need to update the docs in the same fashion you would need to change the code as it was before this refactoring, but updating docs could become an operation that will not create a version bump.

Comment (FelixMZ2018) [reply src/device/functionality/calibration/update.js]: body won, payload is only used in some tests

**Review by vdiezel — APPROVED** [review]
