### PR TITLE
fix: add query params to device user list

### LINKED ISSUE #145: add query params to user.devices.list

### PR DESCRIPTION
**Pull request by FelixMZ2018**
patch: add query params to device user list

- closes #145

### CODE REVIEW

File: src/user/device/list.js [hunk 1]
```diff
@@ -14,5 +14,5 @@ const { DEFAULT_REQ_OPTS } = require('../../utils/defaultReqOpts')
  */
 
 module.exports = serializeAxiosResponse(
-  ({ userId }) => API.get('user', `${userId}/devices`, DEFAULT_REQ_OPTS),
+  ({ userId, queryStringParameters }) => API.get('user', `${userId}/devices`, { queryStringParameters, ...DEFAULT_REQ_OPTS }),
```
Comment (FelixMZ2018) [inline src/user/device/list.js:17]: if we go by convention this should be (userId, { queryStringParameters}) but that would make it a breaking change so I'm keeping it as is

**Review by lev-leontyev-ospin — APPROVED** [review]
